name: Multi_VPS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/Multi_VPS/main/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/Multi_VPS/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/Multi_VPS/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/Multi_VPS/main/browser.bat -OutFile browser.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:TOKEN_1
      env:
        TOKEN_1: ${{ secrets.TOKEN_1 }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy browser.bat C:\Users\Public\Desktop\browser.bat
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Successfully! VPS live 1h
      run: cmd /c loop.bat
